name = "Just Create SMP v0.1"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61d578e7db0b93441c7ef0dec253ccbcb7c60d498ff2627474ca9e9ff0381e44"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "kubejs/data"
