name = "Just Create SMP v0.1"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9a26553e78559ff2c348a3fa3d0d63b823dc5e5d8a0d06b8ce0930ed991bbbb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.139"
