name = "Just Create SMP v0.1"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1de55049f4f4dfbce7b0bb8ffccf8275786e7b82816324ab7f040c1712aaf96"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "kubejs/data"
